### ISSUE TITLE
IntelGraphicsDVMTFixup.kext not being picked up

### ISSUE THREAD

**Issue by Smeedy** [Sher1ocks/IntelGraphicsDVMTFixup#1]
Nice work! But there's something I cannot understand. Working with the pre-build versions you have in the release, nothing happens. I do not see Lilu doing any patching on the logs. Rehabman made some similar [comments](https://www.tonymacx86.com/threads/for-skylake-user-if-use-0x12345678-when-install.218698/page-2).

When I pick up the version pre-build by ReHabMan on bitbucket (a fork of your 1.1.3) I do see the patch and I'm able to boot into the installer. Using your pre-build versions (or my own from XCode) nothing happens.

I'm running on a Lenovo TP T470s i7 by the way. Booting 10.12.5 on a clean stick with minimal kexts (FakeSMC, Lilu, VoodooPS2, HackrNVMe, IntelMausiEthernet) and a clean example HD620 [config.plist](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist) with DVMT 19Mb patched disabled (that is what your kext should do).

tried your
* 1.1.3: nothing happens
* 1.1.6: nothing happens
* 1.1.8: nothing happens

What I haven't tried is to switch the Lilu from rehabman build on bitbucket for the 1.1.4 on [Lilu Github](https://github.com/vit9696/Lilu/releases)

Let me know how I can help.

cheers,
Martijn

**Comment by Sher1ocks** [comment]
hello. i spent busy days. 
please tell me correctly.
1. lilu version
2. dvmt kext

also you have kabylake graphics. you can use hd 620 natively

**Comment by ameenjuz** [comment]
please update your kext to 1.2.2 because lilu is running version 1.2.2
