### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ameenjuz** [Sher1ocks/IntelGraphicsDVMTFixup#4]
please update your kext to 1.2.2 because lily is running version 1.2.2

**Comment by Sher1ocks** [comment]
@anmoolpk updated. please test and tell me about result.
thanks

**Comment by ameenjuz** [comment]
but sir still 1.2.0.kext is available in your GitHub url and I didn't see v 1.2.1 https://github.com/BarbaraPalvin/IntelGraphicsDVMTFixup/releases

**Comment by Sher1ocks** [comment]
@anmoolpk 
[IntelGraphicsDVMTFixup.kext.zip](https://github.com/BarbaraPalvin/IntelGraphicsDVMTFixup/files/1741018/IntelGraphicsDVMTFixup.kext.zip)
please test

**Comment by ameenjuz** [comment]
How to build kext from your project source with xcode or terminal
